spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
pagehelper:
  helper-dialect: mysql
  reasonable: true  #分页合理化参数
